### ISSUE TITLE
RX data was wrong

### ISSUE THREAD

**Issue by nhatnamnguyengtvthcm** [liyanboy74/soft-uart#1]
Hello Bro,
I have try your project but when i send buffer: 0xF8 0x04 0x00 0x00 0x00 0x0A 0x64 0x64  then data i recieved is : 0xF8 0x21 0x04  0x21 0x00  0x21 0x00  0x21 0x00  0x0A  0x21  0x64  0x21  0x64 

Have even you see the same issue?Thanks

**Comment by liyanboy74** [comment]
@nhatnamnguyengtvthcm  Most likely the problem is with your terminal software. Which adds the code 0x21 after each character!
I tried the code but I did not encounter the problem you are talking about!
Code by default set PinA4 as RX & PinB3 as TX with baud rate 9600 and echo any RX data to TX pin.

**Comment by liyanboy74** [comment]
@nhatnamnguyengtvthcm Are that error fixed?
