### ISSUE TITLE
SoftUartHandler  function  0.2 from is 1/5 ?

### ISSUE THREAD

**Issue by teleger** [liyanboy74/soft-uart#2]
so:
SU_Timer++;
if(SU_Timer >= 5){
SU_Timer=0;
}

then  .  set  the 5 is  ???     isn't ?

**Comment by teleger** [comment]
Whether other data can be set ？？

**Comment by liyanboy74** [comment]
I think that will be enough:
```
SU_Timer++;
if(SU_Timer == 5)SU_Timer=0;
```
Thanks.
