### ISSUE TITLE
Receive data anytime 

### ISSUE THREAD

**Issue by ndhung0903** [liyanboy74/soft-uart#4]
Can you help me with the issue when I want to be ready to receive with external interrupts on Rx_Pin?

**Comment by liyanboy74** [comment]
[this](https://github.com/liyanboy74/soft-uart/blob/7d1d8a21a1d0515fbc58007e1e5a394d42b06108/softuart.c#L226C8-L226C17) section of code run in interrupt if any character successfully received and change the TX buffer index for next character.
this function can't have delay and must run faster as possible, so you can write small code for run in this section or set flag and write timer interrupt for check flag for big works ...

**Comment by liyanboy74** [comment]
After receiving is activated, all data will be automatically received and stored in the buffer.

**Comment by orcino** [comment]
Hi friend, does the SoftUartPuts function only send strings? How do I send numbers in hex? I'm initially in C.

**Comment by liyanboy74** [comment]
Hi.
No! ,SoftUartPuts function send everything! just get him length of data and address of that! 😅
