### ISSUE TITLE
Interrupt interval vs. baud rate

### ISSUE THREAD

**Issue by pastaclub** [liyanboy74/soft-uart#5]
If I understand correctly, the code fires interrupts at a constant frequency, during which you sample the inputs, detect start bits, determine the time slot (0..4) for reading the data bits on a given input, and send if there is outgoing data.

This is different from other implementations which have an interrupt triggered by the edge of the start bit (not a timer) and then read data via a timer interrupt set up when the start bit is detected to hit exactly the middle of the data bits.

In your implementation, you get the benefit of many inputs at the cost of timing accuracy, since you will not sample in the middle of the data bit but rather at the fixed time slot that's closest to it. So the higher the oversampling, the closer you get to that middle.

(did I understand everything correctly?)

Now my question is: how did you get to factor 5x for oversampling? why that number? Let's say you did 3x oversampling, would that not be good enough? Did you do calculations on how much the frequencies can deviate from the ideal value while still sampling the correct bit?

**Comment by liyanboy74** [comment]
Yes, you get the point!
It was a idea for implement multi software UART without pin interrupt and just by one timer! ,for resolve complexity of parallel receiving data on any time of any chanel. as you know, if i choose 3x for oversampling, maybe beside of edge i set the flag and start for receiving and in test i saw how that can make big error and lost all the packet! in that project the data was important for me and i do not risk for that!

**Comment by pastaclub** [comment]
That's a great approach. But it SHOULD work with less oversampling and you can probably make it work.

I think the problem lies in SoftUartScanRxPorts(). You sample the RX pins in a for-loop, one after the other. But the run-time of the loop iterations is not constant. There is an if-clause and the branch is sometimes taken, sometimes not. If it is taken, the processor spends more time in the branch and then it reads the next RX pin later. Then on the next timer event it may not take the branch and read the pin earlier. If the point in time where you sample is near the edge of the data bit, you sample the wrong data bit. The actual interval of your pin-sampling varies the most in UART 7 so this UART is the most unreliable.

To fix this, you can sample all RX pins at the same time (if the chip allows you to read them all in one operation) or at least have a dedicated for-loop ONLY for reading the pins, and then ANOTHER for-loop for processing.

I assume that if you fix this, you can get away with less oversampling, thus use less processing time for the UART and archieve higher baudrates.

**Comment by liyanboy74** [comment]
Thanks
